// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QemuXplorer.Data;

#nullable disable

namespace QemuXplorer.Data.Migrations
{
    [DbContext(typeof(QemuXplorerDbContext))]
    [Migration("20260912093247_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("QemuXplorer.Models.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("QemuXplorer.Models.Entities.DiskDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CacheMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Format")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Interface")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBootDevice")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCdRom")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSnapshotMode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VmId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VmId");

                    b.ToTable("DiskDevices");
                });

            modelBuilder.Entity("QemuXplorer.Models.Entities.NetworkAdapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BackendType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BridgeInterface")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HostForwardingRules")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Model")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TapInterface")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VmId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VmId");

                    b.ToTable("NetworkAdapters");
                });

            modelBuilder.Entity("QemuXplorer.Models.Entities.QemuInstallation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BinaryDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("QemuInstallations");
                });

            modelBuilder.Entity("QemuXplorer.Models.Entities.UsbDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPassthrough")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("VendorId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VmId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VmId");

                    b.ToTable("UsbDevices");
                });

            modelBuilder.Entity("QemuXplorer.Models.Entities.VirtualMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Architecture")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableHvf")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableKvm")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableWhpx")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtraArguments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("FallbackToTcg")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MachineType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VirtualMachines");
                });

            modelBuilder.Entity("QemuXplorer.Models.Entities.DiskDevice", b =>
                {
                    b.HasOne("QemuXplorer.Models.Entities.VirtualMachine", "VirtualMachine")
                        .WithMany("Disks")
                        .HasForeignKey("VmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VirtualMachine");
                });

            modelBuilder.Entity("QemuXplorer.Models.Entities.NetworkAdapter", b =>
                {
                    b.HasOne("QemuXplorer.Models.Entities.VirtualMachine", "VirtualMachine")
                        .WithMany("NetworkAdapters")
                        .HasForeignKey("VmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VirtualMachine");
                });

            modelBuilder.Entity("QemuXplorer.Models.Entities.UsbDevice", b =>
                {
                    b.HasOne("QemuXplorer.Models.Entities.VirtualMachine", "VirtualMachine")
                        .WithMany("UsbDevices")
                        .HasForeignKey("VmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VirtualMachine");
                });

            modelBuilder.Entity("QemuXplorer.Models.Entities.VirtualMachine", b =>
                {
                    b.OwnsOne("QemuXplorer.Models.Entities.CpuConfig", "Cpu", b1 =>
                        {
                            b1.Property<Guid>("VirtualMachineId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Cores")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Count")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Sockets")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Threads")
                                .HasColumnType("INTEGER");

                            b1.HasKey("VirtualMachineId");

                            b1.ToTable("VirtualMachines");

                            b1.WithOwner()
                                .HasForeignKey("VirtualMachineId");
                        });

                    b.OwnsOne("QemuXplorer.Models.Entities.DisplayConfig", "Display", b1 =>
                        {
                            b1.Property<Guid>("VirtualMachineId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsFullscreen")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IsGLEnabled")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("SpicePort")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("VgaModel")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("VncAddress")
                                .HasColumnType("TEXT");

                            b1.Property<int>("VncPort")
                                .HasColumnType("INTEGER");

                            b1.HasKey("VirtualMachineId");

                            b1.ToTable("VirtualMachines");

                            b1.WithOwner()
                                .HasForeignKey("VirtualMachineId");
                        });

                    b.OwnsOne("QemuXplorer.Models.Entities.MemoryConfig", "Memory", b1 =>
                        {
                            b1.Property<Guid>("VirtualMachineId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("HotplugSlots")
                                .HasColumnType("INTEGER");

                            b1.Property<long>("SizeMB")
                                .HasColumnType("INTEGER");

                            b1.HasKey("VirtualMachineId");

                            b1.ToTable("VirtualMachines");

                            b1.WithOwner()
                                .HasForeignKey("VirtualMachineId");
                        });

                    b.Navigation("Cpu")
                        .IsRequired();

                    b.Navigation("Display")
                        .IsRequired();

                    b.Navigation("Memory")
                        .IsRequired();
                });

            modelBuilder.Entity("QemuXplorer.Models.Entities.VirtualMachine", b =>
                {
                    b.Navigation("Disks");

                    b.Navigation("NetworkAdapters");

                    b.Navigation("UsbDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
