<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>QEmuXlorer.Core.Tests</AssemblyName>
    <RootNamespace>QEmuXlorer.Core.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
    
  <ItemGroup>
    <ProjectReference Include="..\..\src\QEmuXlorer.Core\QEmuXlorer.Core.csproj" />
    <ProjectReference Include="..\..\src\QEmuXlorer.Models\QEmuXlorer.Models.csproj" />
  </ItemGroup>
    
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>
    
</Project>
