// <auto-generated>
// Generated by tools/dump-machine-types.py from `qemu-system-<arch> -M help`.
// Source: QEMU emulator version 11.1.0 (v11.1.0-12130-ge470268ff4)
//
// Only canonical machine names are listed. QEMU also accepts versioned variants such as
// pc-q35-9.2 or virt-8.1; they are excluded because they would add hundreds of near-duplicate
// members. VirtualMachine.MachineType stays a string precisely so those, and machines from a
// QEMU build this list does not know about, remain usable.
//
// A machine belongs to EVERY architecture whose emulator offers it: 96 of these 127 are
// shared, so the relation is many-to-many and cannot be expressed by Display.GroupName.
// </auto-generated>

using System.ComponentModel.DataAnnotations;

namespace QemuXplorer.Models.Enums;

/// <summary>
/// Canonical QEMU machine types. <see cref="MachineAttribute"/> carries the QEMU name and the
/// architectures that accept it; use <c>MachineCatalog</c> to query them.
/// </summary>
public enum MachineType
{
    // ---- x86 / i386 ----
    [Display(Name = "q35", Description = "Standard PC (Q35 + ICH9, 2009)")]
    [Machine("q35", GuestArchitecture.X86_64, GuestArchitecture.I386)]
    q35,
    [Display(Name = "pc", Description = "Standard PC (i440FX + PIIX, 1996)")]
    [Machine("pc", GuestArchitecture.X86_64, GuestArchitecture.I386)]
    pc,
    [Display(Name = "microvm", Description = "microvm (i386)")]
    [Machine("microvm", GuestArchitecture.X86_64, GuestArchitecture.I386)]
    microvm,
    [Display(Name = "isapc", Description = "ISA-only PC")]
    [Machine("isapc", GuestArchitecture.X86_64, GuestArchitecture.I386)]
    isapc,

    // ---- ARM (aarch64 and arm) ----
    [Display(Name = "virt", Description = "QEMU 11.1 ARM Virtual Machine")]
    [Machine("virt", GuestArchitecture.Aarch64, GuestArchitecture.Arm, GuestArchitecture.RiscV64, GuestArchitecture.RiscV32)]
    virt,
    [Display(Name = "sbsa-ref", Description = "QEMU 'SBSA Reference' ARM Virtual Machine")]
    [Machine("sbsa-ref", GuestArchitecture.Aarch64)]
    sbsa_ref,
    [Display(Name = "amd-versal-virt", Description = "AMD Versal Virtual development board")]
    [Machine("amd-versal-virt", GuestArchitecture.Aarch64)]
    amd_versal_virt,
    [Display(Name = "amd-versal2-virt", Description = "AMD Versal Gen 2 Virtual development board")]
    [Machine("amd-versal2-virt", GuestArchitecture.Aarch64)]
    amd_versal2_virt,
    [Display(Name = "anacapa-bmc", Description = "Facebook Anacapa BMC (Cortex-A7)")]
    [Machine("anacapa-bmc", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    anacapa_bmc,
    [Display(Name = "ast1030-evb", Description = "Aspeed AST1030 MiniBMC (Cortex-M4)")]
    [Machine("ast1030-evb", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    ast1030_evb,
    [Display(Name = "ast1040-evb", Description = "Aspeed AST1040 BIC EVB (Cortex-M4F)")]
    [Machine("ast1040-evb", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    ast1040_evb,
    [Display(Name = "ast1060-evb", Description = "Aspeed AST1060 Platform Root of Trust (Cortex-M4)")]
    [Machine("ast1060-evb", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    ast1060_evb,
    [Display(Name = "ast2500-evb", Description = "Aspeed AST2500 EVB (ARM1176)")]
    [Machine("ast2500-evb", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    ast2500_evb,
    [Display(Name = "ast2600-evb", Description = "Aspeed AST2600 EVB (Cortex-A7)")]
    [Machine("ast2600-evb", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    ast2600_evb,
    [Display(Name = "ast2700-evb", Description = "Aspeed AST2700 A2 EVB (Cortex-A35)")]
    [Machine("ast2700-evb", GuestArchitecture.Aarch64)]
    ast2700_evb,
    [Display(Name = "ast2700a1-evb", Description = "Aspeed AST2700 A1 EVB (Cortex-A35)")]
    [Machine("ast2700a1-evb", GuestArchitecture.Aarch64)]
    ast2700a1_evb,
    [Display(Name = "ast2700a2-evb", Description = "Aspeed AST2700 A2 EVB (Cortex-A35)")]
    [Machine("ast2700a2-evb", GuestArchitecture.Aarch64)]
    ast2700a2_evb,
    [Display(Name = "ast2700fc", Description = "ast2700 full core support")]
    [Machine("ast2700fc", GuestArchitecture.Aarch64)]
    ast2700fc,
    [Display(Name = "b-l475e-iot01a", Description = "B-L475E-IOT01A Discovery Kit (Cortex-M4)")]
    [Machine("b-l475e-iot01a", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    b_l475e_iot01a,
    [Display(Name = "bletchley-bmc", Description = "Facebook Bletchley BMC (Cortex-A7)")]
    [Machine("bletchley-bmc", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    bletchley_bmc,
    [Display(Name = "bpim2u", Description = "Bananapi M2U (Cortex-A7)")]
    [Machine("bpim2u", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    bpim2u,
    [Display(Name = "canon-a1100", Description = "Canon PowerShot A1100 IS (ARM946)")]
    [Machine("canon-a1100", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    canon_a1100,
    [Display(Name = "catalina-bmc", Description = "Facebook Catalina BMC (Cortex-A7)")]
    [Machine("catalina-bmc", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    catalina_bmc,
    [Display(Name = "collie", Description = "Sharp SL-5500 (Collie) PDA (SA-1110)")]
    [Machine("collie", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    collie,
    [Display(Name = "cubieboard", Description = "cubietech cubieboard (Cortex-A8)")]
    [Machine("cubieboard", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    cubieboard,
    [Display(Name = "emcraft-sf2", Description = "SmartFusion2 SOM kit from Emcraft (M2S010)")]
    [Machine("emcraft-sf2", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    emcraft_sf2,
    [Display(Name = "fby35-bmc", Description = "Facebook fby35 BMC (Cortex-A7)")]
    [Machine("fby35-bmc", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    fby35_bmc,
    [Display(Name = "fuji-bmc", Description = "Facebook Fuji BMC (Cortex-A7)")]
    [Machine("fuji-bmc", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    fuji_bmc,
    [Display(Name = "g220a-bmc", Description = "Bytedance G220A BMC (ARM1176)")]
    [Machine("g220a-bmc", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    g220a_bmc,
    [Display(Name = "gb200nvl-bmc", Description = "Nvidia GB200NVL BMC (Cortex-A7)")]
    [Machine("gb200nvl-bmc", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    gb200nvl_bmc,
    [Display(Name = "imx25-pdk", Description = "ARM i.MX25 PDK board (ARM926)")]
    [Machine("imx25-pdk", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    imx25_pdk,
    [Display(Name = "imx8mm-evk", Description = "NXP i.MX 8MM EVK Board")]
    [Machine("imx8mm-evk", GuestArchitecture.Aarch64)]
    imx8mm_evk,
    [Display(Name = "imx8mp-evk", Description = "NXP i.MX 8M Plus EVK Board")]
    [Machine("imx8mp-evk", GuestArchitecture.Aarch64)]
    imx8mp_evk,
    [Display(Name = "integratorcp", Description = "ARM Integrator/CP (ARM926EJ-S)")]
    [Machine("integratorcp", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    integratorcp,
    [Display(Name = "kudo-bmc", Description = "Kudo BMC (Cortex-A9)")]
    [Machine("kudo-bmc", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    kudo_bmc,
    [Display(Name = "kzm", Description = "ARM KZM Emulation Baseboard (ARM1136)")]
    [Machine("kzm", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    kzm,
    [Display(Name = "lm3s6965evb", Description = "Stellaris LM3S6965EVB (Cortex-M3)")]
    [Machine("lm3s6965evb", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    lm3s6965evb,
    [Display(Name = "lm3s811evb", Description = "Stellaris LM3S811EVB (Cortex-M3)")]
    [Machine("lm3s811evb", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    lm3s811evb,
    [Display(Name = "max78000fthr", Description = "MAX78000FTHR Board (Cortex-M4 / (Unimplemented) RISC-V)")]
    [Machine("max78000fthr", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    max78000fthr,
    [Display(Name = "mcimx6ul-evk", Description = "Freescale i.MX6UL Evaluation Kit (Cortex-A7)")]
    [Machine("mcimx6ul-evk", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    mcimx6ul_evk,
    [Display(Name = "mcimx7d-sabre", Description = "Freescale i.MX7 DUAL SABRE (Cortex-A7)")]
    [Machine("mcimx7d-sabre", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    mcimx7d_sabre,
    [Display(Name = "microbit", Description = "BBC micro:bit (Cortex-M0)")]
    [Machine("microbit", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    microbit,
    [Display(Name = "mori-bmc", Description = "Mori BMC (Cortex-A9)")]
    [Machine("mori-bmc", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    mori_bmc,
    [Display(Name = "mps2-an385", Description = "ARM MPS2 with AN385 FPGA image for Cortex-M3")]
    [Machine("mps2-an385", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    mps2_an385,
    [Display(Name = "mps2-an386", Description = "ARM MPS2 with AN386 FPGA image for Cortex-M4")]
    [Machine("mps2-an386", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    mps2_an386,
    [Display(Name = "mps2-an500", Description = "ARM MPS2 with AN500 FPGA image for Cortex-M7")]
    [Machine("mps2-an500", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    mps2_an500,
    [Display(Name = "mps2-an505", Description = "ARM MPS2 with AN505 FPGA image for Cortex-M33")]
    [Machine("mps2-an505", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    mps2_an505,
    [Display(Name = "mps2-an511", Description = "ARM MPS2 with AN511 DesignStart FPGA image for Cortex-M3")]
    [Machine("mps2-an511", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    mps2_an511,
    [Display(Name = "mps2-an521", Description = "ARM MPS2 with AN521 FPGA image for dual Cortex-M33")]
    [Machine("mps2-an521", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    mps2_an521,
    [Display(Name = "mps3-an524", Description = "ARM MPS3 with AN524 FPGA image for dual Cortex-M33")]
    [Machine("mps3-an524", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    mps3_an524,
    [Display(Name = "mps3-an536", Description = "ARM MPS3 with AN536 FPGA image for Cortex-R52")]
    [Machine("mps3-an536", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    mps3_an536,
    [Display(Name = "mps3-an547", Description = "ARM MPS3 with AN547 FPGA image for Cortex-M55")]
    [Machine("mps3-an547", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    mps3_an547,
    [Display(Name = "musca-a", Description = "ARM Musca-A board (dual Cortex-M33)")]
    [Machine("musca-a", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    musca_a,
    [Display(Name = "musca-b1", Description = "ARM Musca-B1 board (dual Cortex-M33)")]
    [Machine("musca-b1", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    musca_b1,
    [Display(Name = "musicpal", Description = "Marvell 88w8618 / MusicPal (ARM926EJ-S)")]
    [Machine("musicpal", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    musicpal,
    [Display(Name = "netduino2", Description = "Netduino 2 Machine (Cortex-M3)")]
    [Machine("netduino2", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    netduino2,
    [Display(Name = "netduinoplus2", Description = "Netduino Plus 2 Machine (Cortex-M4)")]
    [Machine("netduinoplus2", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    netduinoplus2,
    [Display(Name = "npcm750-evb", Description = "Nuvoton NPCM750 Evaluation Board (Cortex-A9)")]
    [Machine("npcm750-evb", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    npcm750_evb,
    [Display(Name = "npcm845-evb", Description = "Nuvoton NPCM845 Evaluation Board (Cortex-A35)")]
    [Machine("npcm845-evb", GuestArchitecture.Aarch64)]
    npcm845_evb,
    [Display(Name = "nuri", Description = "Samsung NURI board (Exynos4210)")]
    [Machine("nuri", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    nuri,
    [Display(Name = "olimex-stm32-h405", Description = "Olimex STM32-H405 (Cortex-M4)")]
    [Machine("olimex-stm32-h405", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    olimex_stm32_h405,
    [Display(Name = "orangepi-pc", Description = "Orange Pi PC (Cortex-A7)")]
    [Machine("orangepi-pc", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    orangepi_pc,
    [Display(Name = "palmetto-bmc", Description = "OpenPOWER Palmetto BMC (ARM926EJ-S)")]
    [Machine("palmetto-bmc", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    palmetto_bmc,
    [Display(Name = "quanta-gbs-bmc", Description = "Quanta GBS (Cortex-A9)")]
    [Machine("quanta-gbs-bmc", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    quanta_gbs_bmc,
    [Display(Name = "quanta-gsj", Description = "Quanta GSJ (Cortex-A9)")]
    [Machine("quanta-gsj", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    quanta_gsj,
    [Display(Name = "quanta-q71l-bmc", Description = "Quanta-Q71l BMC (ARM926EJ-S)")]
    [Machine("quanta-q71l-bmc", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    quanta_q71l_bmc,
    [Display(Name = "rainier-bmc", Description = "IBM Rainier BMC (Cortex-A7)")]
    [Machine("rainier-bmc", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    rainier_bmc,
    [Display(Name = "raspi0", Description = "Raspberry Pi Zero (revision 1.2)")]
    [Machine("raspi0", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    raspi0,
    [Display(Name = "raspi1ap", Description = "Raspberry Pi A+ (revision 1.1)")]
    [Machine("raspi1ap", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    raspi1ap,
    [Display(Name = "raspi2b", Description = "Raspberry Pi 2B (revision 1.1)")]
    [Machine("raspi2b", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    raspi2b,
    [Display(Name = "raspi3ap", Description = "Raspberry Pi 3A+ (revision 1.0)")]
    [Machine("raspi3ap", GuestArchitecture.Aarch64)]
    raspi3ap,
    [Display(Name = "raspi3b", Description = "Raspberry Pi 3B (revision 1.2)")]
    [Machine("raspi3b", GuestArchitecture.Aarch64)]
    raspi3b,
    [Display(Name = "raspi4b", Description = "Raspberry Pi 4B (revision 1.5)")]
    [Machine("raspi4b", GuestArchitecture.Aarch64)]
    raspi4b,
    [Display(Name = "realview-eb", Description = "ARM RealView Emulation Baseboard (ARM926EJ-S)")]
    [Machine("realview-eb", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    realview_eb,
    [Display(Name = "realview-eb-mpcore", Description = "ARM RealView Emulation Baseboard (ARM11MPCore)")]
    [Machine("realview-eb-mpcore", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    realview_eb_mpcore,
    [Display(Name = "realview-pb-a8", Description = "ARM RealView Platform Baseboard for Cortex-A8")]
    [Machine("realview-pb-a8", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    realview_pb_a8,
    [Display(Name = "realview-pbx-a9", Description = "ARM RealView Platform Baseboard Explore for Cortex-A9")]
    [Machine("realview-pbx-a9", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    realview_pbx_a9,
    [Display(Name = "romulus-bmc", Description = "OpenPOWER Romulus BMC (ARM1176)")]
    [Machine("romulus-bmc", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    romulus_bmc,
    [Display(Name = "sabrelite", Description = "Freescale i.MX6 Quad SABRE Lite Board (Cortex-A9)")]
    [Machine("sabrelite", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    sabrelite,
    [Display(Name = "smdkc210", Description = "Samsung SMDKC210 board (Exynos4210)")]
    [Machine("smdkc210", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    smdkc210,
    [Display(Name = "stm32vldiscovery", Description = "ST STM32VLDISCOVERY (Cortex-M3)")]
    [Machine("stm32vldiscovery", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    stm32vldiscovery,
    [Display(Name = "supermicrox11-bmc", Description = "Supermicro X11 BMC (ARM926EJ-S)")]
    [Machine("supermicrox11-bmc", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    supermicrox11_bmc,
    [Display(Name = "sx1", Description = "Siemens SX1 (OMAP310) V2")]
    [Machine("sx1", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    sx1,
    [Display(Name = "sx1-v1", Description = "Siemens SX1 (OMAP310) V1")]
    [Machine("sx1-v1", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    sx1_v1,
    [Display(Name = "tiogapass-bmc", Description = "Facebook Tiogapass BMC (ARM1176)")]
    [Machine("tiogapass-bmc", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    tiogapass_bmc,
    [Display(Name = "versatileab", Description = "ARM Versatile/AB (ARM926EJ-S)")]
    [Machine("versatileab", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    versatileab,
    [Display(Name = "versatilepb", Description = "ARM Versatile/PB (ARM926EJ-S)")]
    [Machine("versatilepb", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    versatilepb,
    [Display(Name = "vexpress-a15", Description = "ARM Versatile Express for Cortex-A15")]
    [Machine("vexpress-a15", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    vexpress_a15,
    [Display(Name = "vexpress-a9", Description = "ARM Versatile Express for Cortex-A9")]
    [Machine("vexpress-a9", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    vexpress_a9,
    [Display(Name = "witherspoon-bmc", Description = "OpenPOWER Witherspoon BMC (ARM1176)")]
    [Machine("witherspoon-bmc", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    witherspoon_bmc,
    [Display(Name = "xilinx-zynq-a9", Description = "Xilinx Zynq 7000 Platform Baseboard for Cortex-A9")]
    [Machine("xilinx-zynq-a9", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    xilinx_zynq_a9,
    [Display(Name = "xlnx-versal-virt", Description = "AMD Versal Virtual development board")]
    [Machine("xlnx-versal-virt", GuestArchitecture.Aarch64)]
    xlnx_versal_virt,
    [Display(Name = "xlnx-zcu102", Description = "Xilinx ZynqMP ZCU102 board with 4xA53s and 2xR5Fs based on the value of smp")]
    [Machine("xlnx-zcu102", GuestArchitecture.Aarch64)]
    xlnx_zcu102,
    [Display(Name = "yosemitev2-bmc", Description = "Facebook YosemiteV2 BMC (ARM1176)")]
    [Machine("yosemitev2-bmc", GuestArchitecture.Aarch64, GuestArchitecture.Arm)]
    yosemitev2_bmc,

    // ---- RISC-V ----
    [Display(Name = "boston-aia", Description = "MIPS Boston-aia")]
    [Machine("boston-aia", GuestArchitecture.RiscV64)]
    boston_aia,
    [Display(Name = "k230", Description = "RISC-V Board compatible with Kendryte K230 SDK")]
    [Machine("k230", GuestArchitecture.RiscV64)]
    k230,
    [Display(Name = "shakti_c", Description = "RISC-V Board compatible with Shakti SDK")]
    [Machine("shakti_c", GuestArchitecture.RiscV64, IsDeprecated = true)]
    shakti_c,
    [Display(Name = "sifive_e", Description = "RISC-V Board compatible with SiFive E SDK")]
    [Machine("sifive_e", GuestArchitecture.RiscV64, GuestArchitecture.RiscV32)]
    sifive_e,
    [Display(Name = "sifive_u", Description = "RISC-V Board compatible with SiFive U SDK")]
    [Machine("sifive_u", GuestArchitecture.RiscV64, GuestArchitecture.RiscV32)]
    sifive_u,
    [Display(Name = "spike", Description = "RISC-V Spike board")]
    [Machine("spike", GuestArchitecture.RiscV64, GuestArchitecture.RiscV32)]
    spike,
    [Display(Name = "tt-atlantis", Description = "Tenstorrent Atlantis RISC-V SoC (Experimental)")]
    [Machine("tt-atlantis", GuestArchitecture.RiscV64)]
    tt_atlantis,
    [Display(Name = "xiangshan-kunminghu", Description = "RISC-V Board compatible with the Xiangshan Kunminghu FPGA prototype platform")]
    [Machine("xiangshan-kunminghu", GuestArchitecture.RiscV64)]
    xiangshan_kunminghu,

    // ---- RISC-V (32-bit only) ----
    [Display(Name = "opentitan", Description = "RISC-V Board compatible with OpenTitan")]
    [Machine("opentitan", GuestArchitecture.RiscV32)]
    opentitan,

    // ---- PowerPC ----
    [Display(Name = "pseries", Description = "pSeries Logical Partition (PAPR compliant)")]
    [Machine("pseries", GuestArchitecture.Ppc64)]
    pseries,
    [Display(Name = "40p", Description = "IBM RS/6000 7020 (40p)")]
    [Machine("40p", GuestArchitecture.Ppc64, GuestArchitecture.Ppc)]
    _40p,
    [Display(Name = "amigaone", Description = "Eyetech AmigaOne/Mai Logic Teron")]
    [Machine("amigaone", GuestArchitecture.Ppc64, GuestArchitecture.Ppc)]
    amigaone,
    [Display(Name = "bamboo", Description = "bamboo")]
    [Machine("bamboo", GuestArchitecture.Ppc64, GuestArchitecture.Ppc)]
    bamboo,
    [Display(Name = "g3beige", Description = "Heathrow based PowerMac")]
    [Machine("g3beige", GuestArchitecture.Ppc64, GuestArchitecture.Ppc)]
    g3beige,
    [Display(Name = "mac99", Description = "Mac99 based PowerMac")]
    [Machine("mac99", GuestArchitecture.Ppc64, GuestArchitecture.Ppc)]
    mac99,
    [Display(Name = "mpc8544ds", Description = "mpc8544ds")]
    [Machine("mpc8544ds", GuestArchitecture.Ppc64, GuestArchitecture.Ppc)]
    mpc8544ds,
    [Display(Name = "pegasos1", Description = "Genesi/bPlan Pegasos I")]
    [Machine("pegasos1", GuestArchitecture.Ppc64, GuestArchitecture.Ppc)]
    pegasos1,
    [Display(Name = "pegasos2", Description = "Genesi/bPlan Pegasos II")]
    [Machine("pegasos2", GuestArchitecture.Ppc64, GuestArchitecture.Ppc)]
    pegasos2,
    [Display(Name = "powernv", Description = "IBM PowerNV (Non-Virtualized) Power11")]
    [Machine("powernv", GuestArchitecture.Ppc64)]
    powernv,
    [Display(Name = "powernv10", Description = "IBM PowerNV (Non-Virtualized) POWER10")]
    [Machine("powernv10", GuestArchitecture.Ppc64)]
    powernv10,
    [Display(Name = "powernv10-rainier", Description = "IBM PowerNV (Non-Virtualized) POWER10 Rainier")]
    [Machine("powernv10-rainier", GuestArchitecture.Ppc64)]
    powernv10_rainier,
    [Display(Name = "powernv11", Description = "IBM PowerNV (Non-Virtualized) Power11")]
    [Machine("powernv11", GuestArchitecture.Ppc64)]
    powernv11,
    [Display(Name = "powernv8", Description = "IBM PowerNV (Non-Virtualized) POWER8")]
    [Machine("powernv8", GuestArchitecture.Ppc64)]
    powernv8,
    [Display(Name = "powernv9", Description = "IBM PowerNV (Non-Virtualized) POWER9")]
    [Machine("powernv9", GuestArchitecture.Ppc64)]
    powernv9,
    [Display(Name = "ppce500", Description = "generic paravirt e500 platform")]
    [Machine("ppce500", GuestArchitecture.Ppc64, GuestArchitecture.Ppc)]
    ppce500,
    [Display(Name = "ppe42_machine", Description = "PPE42 Test Machine")]
    [Machine("ppe42_machine", GuestArchitecture.Ppc64, GuestArchitecture.Ppc)]
    ppe42_machine,
    [Display(Name = "sam460ex", Description = "aCube Sam460ex")]
    [Machine("sam460ex", GuestArchitecture.Ppc64, GuestArchitecture.Ppc)]
    sam460ex,
    [Display(Name = "virtex-ml507", Description = "Xilinx Virtex ML507 reference design")]
    [Machine("virtex-ml507", GuestArchitecture.Ppc64, GuestArchitecture.Ppc)]
    virtex_ml507,

    // ---- MIPS ----
    [Display(Name = "malta", Description = "MIPS Malta Core LV")]
    [Machine("malta", GuestArchitecture.Mips, GuestArchitecture.Mips64)]
    malta,

    // ---- MIPS (64-bit only) ----
    [Display(Name = "magnum", Description = "MIPS Magnum")]
    [Machine("magnum", GuestArchitecture.Mips64)]
    magnum,
    [Display(Name = "pica61", Description = "Acer Pica 61")]
    [Machine("pica61", GuestArchitecture.Mips64)]
    pica61,

    // ---- s390x ----
    [Display(Name = "s390-ccw-virtio", Description = "Virtual s390x machine (version 11.1)")]
    [Machine("s390-ccw-virtio", GuestArchitecture.S390x)]
    s390_ccw_virtio,

    // ---- Every architecture ----
    [Display(Name = "none", Description = "empty machine")]
    [Machine("none", GuestArchitecture.X86_64, GuestArchitecture.I386, GuestArchitecture.Aarch64, GuestArchitecture.Arm, GuestArchitecture.RiscV64, GuestArchitecture.RiscV32, GuestArchitecture.Ppc64, GuestArchitecture.Ppc, GuestArchitecture.Mips, GuestArchitecture.Mips64, GuestArchitecture.S390x)]
    none,
}
