"""Regenerate QemuXplorer.Models/Enums/MachineType.cs from a real QEMU install.

QEMU's machine list is build-specific: Xen machines only appear in Xen-enabled builds, and
old boards are removed between releases. So this list is a snapshot, taken from whatever
QEMU the caller points at.

    python tools/dump-machine-types.py "/c/Program Files/qemu" > src/QemuXplorer.Models/Enums/MachineType.cs
"""
import collections
import os
import re
import subprocess
import sys

ARCHS = ["x86_64", "i386", "aarch64", "arm", "riscv64", "riscv32",
         "ppc64", "ppc", "mips", "mips64", "s390x"]

ARCH_CS = {"x86_64": "X86_64", "i386": "I386", "aarch64": "Aarch64", "arm": "Arm",
           "riscv64": "RiscV64", "riscv32": "RiscV32", "ppc64": "Ppc64", "ppc": "Ppc",
           "mips": "Mips", "mips64": "Mips64", "s390x": "S390x"}

GROUP = {"x86_64": "x86 / i386", "i386": "x86 / i386", "aarch64": "ARM (aarch64 and arm)",
         "arm": "ARM (32-bit only)", "riscv64": "RISC-V", "riscv32": "RISC-V (32-bit only)",
         "ppc64": "PowerPC", "ppc": "PowerPC (32-bit only)", "mips": "MIPS",
         "mips64": "MIPS (64-bit only)", "s390x": "s390x"}

# Put the machine a user most likely wants first in each group, so default(MachineType)
# and an unsorted picker both land somewhere sensible.
PREFERRED = ["q35", "pc", "microvm", "virt", "sbsa-ref", "pseries", "s390-ccw-virtio", "malta"]

# pc-q35-9.2, virt-8.1 and friends: hundreds of near-duplicates, excluded on purpose.
VERSIONED = re.compile(r"-\d+\.\d+$")


def resolve(qemu_dir, stem):
    """Windows needs the .exe suffix; POSIX does not."""
    for candidate in (os.path.join(qemu_dir, stem), os.path.join(qemu_dir, stem + ".exe")):
        if os.path.exists(candidate):
            return candidate
    return os.path.join(qemu_dir, stem)


def collect(qemu_dir):
    machines = collections.defaultdict(
        lambda: {"desc": "", "archs": [], "deprecated": False})
    for arch in ARCHS:
        exe = resolve(qemu_dir, f"qemu-system-{arch}")
        try:
            raw = subprocess.run([exe, "-M", "help"], capture_output=True, text=True,
                                 timeout=60).stdout
        except (OSError, subprocess.SubprocessError) as exc:
            print(f"warning: skipping {arch}: {exc}", file=sys.stderr)
            continue
        for line in raw.splitlines():
            if not line or line.startswith("Supported machines"):
                continue
            m = re.match(r"^(\S+)\s\s+(.*)$", line)
            if not m or VERSIONED.search(m.group(1)):
                continue
            name, desc = m.group(1), m.group(2).strip()
            deprecated = "(deprecated)" in desc
            desc = desc.replace("(deprecated)", "").replace("(default)", "")
            desc = re.sub(r"\s*\(alias of [^)]*\)", "", desc).strip()
            entry = machines[name]
            if len(desc) > len(entry["desc"]):
                entry["desc"] = desc
            entry["archs"].append(arch)
            entry["deprecated"] |= deprecated
    return machines


def identifier(name):
    ident = re.sub(r"[^0-9A-Za-z]", "_", name)
    return "_" + ident if ident[0].isdigit() else ident


def sort_key(name, info):
    archs = set(info["archs"])
    group = (99, "Every architecture") if len(archs) >= 8 else next(
        ((i, GROUP[a]) for i, a in enumerate(ARCHS) if a in archs), (98, "Other"))
    rank = PREFERRED.index(name) if name in PREFERRED else len(PREFERRED)
    return group[0], rank, name, group[1]


def main():
    qemu_dir = sys.argv[1] if len(sys.argv) > 1 else "/usr/bin"
    machines = collect(qemu_dir)
    if not machines:
        sys.exit("no machines found; is the path to the QEMU binaries correct?")

    rows = sorted(machines.items(), key=lambda kv: sort_key(kv[0], kv[1]))
    version = subprocess.run([resolve(qemu_dir, "qemu-system-x86_64"), "--version"],
                             capture_output=True, text=True).stdout.splitlines()[0]
    shared = sum(1 for _, i in rows if len(set(i["archs"])) > 1)

    print(f"""// <auto-generated>
// Generated by tools/dump-machine-types.py from `qemu-system-<arch> -M help`.
// Source: {version.strip()}
//
// Only canonical machine names are listed. QEMU also accepts versioned variants such as
// pc-q35-9.2 or virt-8.1; they are excluded because they would add hundreds of near-duplicate
// members. VirtualMachine.MachineType stays a string precisely so those, and machines from a
// QEMU build this list does not know about, remain usable.
//
// A machine belongs to EVERY architecture whose emulator offers it: {shared} of these {len(rows)} are
// shared, so the relation is many-to-many and cannot be expressed by Display.GroupName.
// </auto-generated>

using System.ComponentModel.DataAnnotations;

namespace QemuXplorer.Models.Enums;

/// <summary>
/// Canonical QEMU machine types. <see cref="MachineAttribute"/> carries the QEMU name and the
/// architectures that accept it; use <c>MachineCatalog</c> to query them.
/// </summary>
public enum MachineType
{{""")

    current = None
    for i, (name, info) in enumerate(rows):
        group = sort_key(name, info)[3]
        if group != current:
            print(("" if i == 0 else "\n") + f"    // ---- {group} ----")
            current = group
        desc = info["desc"].replace('"', '\\"')
        archs = ", ".join(f"GuestArchitecture.{ARCH_CS[a]}" for a in info["archs"])
        dep = ", IsDeprecated = true" if info["deprecated"] else ""
        print(f'    [Display(Name = "{name}", Description = "{desc}")]' if desc
              else f'    [Display(Name = "{name}")]')
        print(f'    [Machine("{name}", {archs}{dep})]')
        print(f"    {identifier(name)},")
    print("}")


if __name__ == "__main__":
    main()
